### ISSUE TITLE
Remove absolufy-imports

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/cheshire#84]
Absolufy imports doesn't play well with VS Code's automatic import removal and the typical way that imports are used to structure public module interfaces.

**Comment by MarcoGorelli** [comment]
Hey @zaneselvans - just out of interest, what's the issue with integrating with VS Code's automatic import removal? If there's anything I can change on `absolufy-imports`'s side that'd make this better, please do let me know (else, sorry for the noise)

**Comment by MarcoGorelli** [comment]
Hey @zaneselvans - just out of interest, what's the issue with integrating with VS Code's automatic import removal? If there's anything I can change on `absolufy-imports`'s side that'd make this better, please do let me know (else, sorry for the noise)

**Comment by zaneselvans** [comment]
Removed this when switching over to using `ruff` for linting & autoformatting.
